- .env
- src/api/common.controller.js
- src/api/diary.controller.js
- src/axiosTest.js
> [chore] axios 를 위한 controller 구현

- .env
- package-lock.json
- package.json
- src/App.css
- src/App.js
- src/api/common.controller.js
- src/api/survey.controller.js
- src/index.css
- src/pages/Home.js
- src/pages/Survey.js
- src/tailwind.config.js
> [feat] 설문 페이지 틀 구현

- .gitignore
- src/component/ImageDiary/Image.js
- Draggable 경계 추가
- img 태그 `draggable={"false"}` 추가
> [feat] Draggable 경계 추가

- src/pages/Calendar.js
- src/pages/DiaryEdit.js
- src/redux/config/configStore.js
- src/redux/modules/DiaryDate.js
- src/styles/Calendar.css
- src/styles/DiaryEdit.css
- src/styles/diary.css
- 클릭한 날짜 가져오기
- /diarywrite 크기 맞추기
- DiaryEdit 디자인 수정
- Calendar 날짜 전역변수 설정
> Feat/22 일기 작성 기능 구현

- src/pages/Diary.js
- src/pages/DiaryEdit.js
- src/styles/diary.css
> [design]일기장 작성 부분 디자인 수정

- src/component/Header.js
- src/index.css
- index.css 수정
- Header 뒤로가기 오류 수정
- Header 페이지이름 수정
> Refactor/41 전체 scroll, Header.js 수정

- package-lock.json
- package.json
- src/App.js
- src/pages/DiaryTest.js
- src/pages/DiaryTestResult.js
- src/pages/Draw.js
- src/styles/SurveyStart.css
- 그림일기 첫페이지, 마지막페이지 화살표 수정
- 일기회상 결과 값 넘겨주기 
- 없음
> Refactor/44 그림일기 화살표, 일기회상 값 넘겨주기

- src/pages/DiaryShow.js
- src/styles/diary.css
- 일기회상, 일기작성 수정
- 일기회상 버튼 클릭시 페이지로 넘어감
- 일기작성 칸에 아이콘 지우기
> Refactor/49 일기회상, 일기작성 수정

- src/api/diary.controller.js
- src/pages/DiaryTest.js
> [feat] 일기회상 api 연동

- src/api/common.controller.js
- src/api/diary.controller.js
- src/pages/Calendar.js
- src/pages/Diary.js
- src/pages/DiaryWrite.js
- 월,일이 9일때, 09가 아닌 9로 전달되는 부분 수정
- 일기 수정 post에서 patch로 수정
- 일기 조회 response 수정
- 일기 저장 api 수정
- 
- 없음
> Refactor/56 일기 API 수정

- src/api/diary.controller.js
- src/pages/DiaryShow.js
- src/pages/DiaryTest.js
-  DiaryShow.js -> 일기회상으로 diaryId 전달
- 없음
> [feat]DiaryShow에서 일기회상으로 diaryId 전달

- src/pages/DiaryTest.js
- src/pages/DiaryTestResult.js
- src/pages/DiaryTestSubmit.js
- 일기회상 결과보러가기 구현
- 홈으로가기 구현
- 결과페이지로 정답배열, 사용자 입력배열 넘겨주기
> feat/63 일기회상 결과보러가기, 홈으로가기 구현

- src/pages/Calendar.js
> feat/67 미래 일기 작성 막아두기

- src/pages/Diary.js
-  일기 띄워주는 부분 -> 일기 길면 짤림
- 없음
> [refactor]일기 표시 수정

- src/pages/DiaryShow.js
- src/pages/Error.js
- 에러페이지로 이동하는 경우 수정
- DiaryShow페이지에서 일기수정하러가기 수정 
- 없음
> Refactor/74 에러페이지, DiaryShow 페이지 

- src/pages/Calendar.js
- src/pages/DiaryTestSubmit.js
- src/pages/DiaryWrite.js
- src/pages/Home.js
- src/pages/gamePages/game2.js
- src/pages/gamePages/game3.js
- src/pages/gamePages/game5.js
- '홈으로가기' 버튼 마진 추가
- 게임 링크 추가
- 일기 작성 막기(다른 달도 확인)
- 일기 작성 시, 콘솔 찍히는 부분 삭제
- Home의 치매진단 -> 치매센터로 수정
- 없음
> Refactor/78 수정

- src/api/survey.controller.js
- src/api/test.controller.js
- 치매진단 URL 수정 
- survey url 추가
- text controller 추가
> [refactor] 치매진단 url 수정

- src/App.js
- src/component/Header.js
- src/component/Navbar.js
- src/index.css
- src/pages/Home.js
- 홈화면 tailwind css 적용
- 헤더 비율, position 수정
- 네브바 비율, position 수정
- 화면크기 비율, 마진 수정
> Refactor/83 홈화면 tailwind css 적용

- src/component/QuizBox.js
- src/pages/Calendar.js
- src/pages/Diary.js
- src/pages/DiaryShow.js
- src/pages/DiaryTest.js
- src/pages/DiaryTestResult.js
- src/redux/config/configStore.js
- src/redux/modules/DiaryInfo.js
- src/styles/QuizBox.css
- 결과 확인 수정
- 일기 수정 후 바로 열면 오류 생김
- 홈으로가기 -> 캘린더로 가기 수정
- Diary 정보 전역변수로 수정(redux)
> Refactor/82 일기회상 제출 페이지 수정 

- src/component/Header.js
- src/component/Navbar.js
-  Header 수정
-  Navbar 수정
- 없음
> Refactor/86 Header, Navbar 반응형으로 수정

- src/App.js
- src/component/Header.js
- src/component/Navbar.js
- src/index.css
> [refactor]전체 틀 수정

- src/App.js
> [refactor] 페이지 이동 시 스크롤 시작 위치 수정

- src/pages/Diary.js
- src/pages/DiaryWrite.js
- Diary 수정 시, 내용이 없으면 알림 띄움
- Diary 작성 시, 내용이 없으면 알림 띄움
- 없음
> [fix]일기 내용 작성하지 않으면 알림 띄움

- src/App.js
- src/index.css
- scroll css 없앰
- App.js "overflow: scroll" 로 수정
- 
- 없음
> [refactor]scroll 수정

- .github/workflows/deploy.yml
- package-lock.json
- package.json
- public/index.html
- 자동화 배포 스크립트 수정
- 자동화 배포에 필요한 요구사항들 설정
> [chore] 자동화 배포 스크립트 수정

- src/component/Loading.js
- src/index.css
- src/pages/Calendar.js
- src/pages/Draw.js
- 그림일기 캔버스 터치 시 스크롤 막기
- 일기 선택 시, 일기 작성 버튼 보였다가 DiaryShow 나옴
- 로딩창 배경 전부로 설정
- 일기회상 시, 문제가 몇 글자인지 안보임 -> 글자 간격 넓히기
- 없음
> Refactor/107 데모 전 수정

- src/App.js
- src/pages/DiaryTestResult.js
- 일기회상 페이지 마진수정
- 스크롤 최상단 수정 
- 없음
> Refactor/109 마진, 스크롤 수정

- src/pages/Calendar.js
> [refactor]일기 선택 시, 렌더링 문제 해결

- src/pages/Calendar.js
> [fix]캘린더 날짜 오류 해결

- package-lock.json
- package.json
> [chore]react-icons 설치

- src/api/common.controller.js
- src/api/diary.controller.js
- src/pages/Diary.js
> Feat/114 일기 삭제 api 연동

- src/App.js
- src/component/BeforeGame.js
- src/component/Modal.js
- src/pages/Games.js
- 게임 시작 전 설명 띄워주기
- 게임별 게임 시작 연결
> Feat/120 게임 시작 전 설명 표시

- src/api/users.controller.js
- src/pages/Login.js
> [feat]로그인 api 연동

- src/api/users.controller.js
- src/pages/Signup.js
- 회원가입 api 연동
- 닉네임 중복확인 api 연동
- 회원가입 완료 후 홈으로 이동
> Feat/123 회원가입 기능 구현

- src/App.js
- src/component/GymButton.js
- src/component/Header.js
- src/pages/Gymnastics.js
- src/pages/GymnasticsVideo.js
- src/pages/Home.js
- 체조 영상 제공 기능 구현
- Header 이름 설정 및 아이콘 변경
> Feat/118 체조 영상 제공 기능

- package-lock.json
- package.json
- src/component/Graph.js
- d3 라이브러리 설치
- d3를 이용한 그래프데이터 시각화 컴포넌트 구현
**Graph 컴포넌트의 props 설명**
```jsx
{
// 그래프 데이터
data,
// 가로 세로 크기 기본값은 반응형
width = "100%", height = "100%",
// 노드의 폰트 사이즈
fondSize = {user: 20, diary: 20, keyword: 20},
// 노드의 크기 keywordConstants는 weight에 곱해지는 상수 (키워드 노드의 가중치에 따라 크기가 달라짐)
nodeSize = {user: 20, diary: 20, keyword: 20, keywordConstants: 1},
// 노드의 색상 (user, diary, keyword)
nodeColor = {user: "red", diary: "green", keyword: "blue"},
// 노드 간격(노드가 서로 밀려나는힘) 음수일 경우 응집력으로 바뀜
spreadForce = 500
}
```
> d3를 이용한 그래프데이터 시각화 컴포넌트 구현

- src/pages/Draw.js
- 예시 그림 띄우기
- 예시 없을 때, 안내문구 띄우기
- 없음
> Feat/130 그림일기 예시 띄우기

- src/pages/SurveyStart.js
- 치매진단 페이지 문구 수정
- 치매진단 페이지 디자인 수정
- 없음
> [refactor]치매진단 페이지 문구 수정

- src/component/ChartGraph.js
- src/pages/Survey.js
- src/pages/SurveyResult.js
- 유효성 에러 글씨 키우기
- chart 마진 추가 
- 없음
> Refactor/152 치매진단 추가 수정

- src/App.js
- src/component/Header.js
- src/layout/MainLayout.js
- src/layout/SubLayout.js
- src/pages/Home.js
- src/pages/Login.js
- src/pages/Signup.js
- src/redux/config/configStore.js
- src/redux/modules/UserInfo.js
- 로그인 후 회원 정보 저장
- 앱 접속 시, 로그인 페이지로 이동
- 회원정보 전역관리
- Layout으로 변경
> Feat/139 로그인 기능 구현

- src/component/Header.js
> [refactor] 진단 결과 헤더 수정

- src/pages/DiaryWrite.js
> [feat]일기 작성 STT 삭제

- src/api/diary.controller.js
- src/api/img.controller.js
- src/component/ImageDiary/Canvas.js
- src/component/ImageDiary/Color.js
- src/component/ImageDiary/Image.js
- src/pages/Diary.js
- src/pages/DiaryShow.js
- src/pages/Draw.js
- src/pages/Draw2.js
- src/pages/PhotoEdit.js
- src/redux/modules/ImageDiary.js
- 그림일기 마우스로도 그릴수 있게
- 그림일기 지우개 에임 수정
- api 호출 수정
- 그림일기 brushSize 기본 값 수정
- draggable bounds 수정
- 키워드 별 사진 띄우기
> Feat/162 그림일기 수정

- src/api/diary.controller.js
- src/pages/Calendar.js
- src/pages/Diary.js
- src/pages/DiaryShow.js
- src/pages/Draw.js
- src/pages/Login.js
- api url 변경
- api 변경으로 발생하는 오류 해결
- 없음
> Refactor/178 api url 변경

- src/component/QuizBox.js
- src/pages/DementiaCenter.js
> [refactor] 치매센터 검색창, 제출답안 수정

- src/api/record.controller.js
- src/component/CompareChart.js
- src/component/SkeletonSurvey.js
- src/layout/MainLayout.js
- src/pages/Home.js
- src/pages/PrevSurveyResult.js
- src/pages/Survey.js
- src/pages/SurveyError.js
- src/pages/SurveyResult.js
- src/pages/SurveyStart.js
- src/styles/Skeleton.css
- 한페이지당 문제 하나로 변경
- 스켈레톤 UI 수정
- 이전 치매진단 결과 보여주기
- 이전진단결과 조회 
- 진단결과 비교 그래프 추가
- 문항이 선택된 경우만 다음페이지로 넘어가도록 수정
- 문제번호 옆으로 화살표 위치 수정
> Refactor/181 치매진단페이지 수정

- .prettierrc
- package-lock.json
- package.json
- src/component/DementiaList.js
- src/hooks/useGetNearByCenter.js
- src/pages/CenterMap.js
- src/pages/DementiaCenter.js
- tailwind.config.js
- 주변 치매 센터 가져오기 리팩토링
- 사용자 위치 가져오기전 주변 치매 센터 검색 불가
- 카카오 맵 remomory 도메인 추가 하여 오류 해결 
- tailwindcss REMEMORY 커스텀 색 추가
> [fix] 카카오 맵 오류 해결 및 주변 치매 센터 가져오기 코드 리팩토링

- src/App.js
- src/pages/DementiaCenter.js
- src/pages/Explain.js
- src/pages/Keyword.js
- 치매센터
- 키워드그래프
- 키워드그래프, 설명 페이지 route 추가
> Refactor/195 페이지 이름 수정 

- src/component/SkeletonSurvey.js
- src/pages/Survey.js
- src/styles/Skeleton.css
> [refactor] 치매진단 스켈레톤 UI 수정

- src/component/Graphs.js
- 키워드 그래프 간격 수정
- 노드 가중치 변경
- 관계값 수정
> [refactor] 키워드 그래프 간격, 노드 가중치, 관계값 수정

- src/pages/PhotoEdit.js
- src/pages/gamePages/BeforeGame.js
> [refactor] 그림 편집 시, 빈 곳 선택하면 취소

- package-lock.json
- package.json
- src/App.js
- src/api/img.controller.js
- src/component/BackGroundSkyButton.js
- src/component/ImageDiary/AIModal.js
- src/component/ImageDiary/Color.js
- src/component/ImageDiary/Palette.js
- src/pages/Calendar/Draw.js
- src/pages/Calendar/HelpForAi.js
- src/pages/ImageDiary/HelpForAi.js
- src/pages/ImageDiary/ShowAiResult.js
- src/pages/Login.js
- src/pages/Signup.js
- src/styles/Login.css
- 그림일기 ui 수정
- 슬라이더 구현
- 키워드 포함 여부 확인
- 사진 투명도 조절
> Design/214 그림일기 ui 수정

- src/App.js
- src/api/diary.controller.js
- src/pages/Calendar/Calendar.js
> Feat/211 캘린더 일기 표시 

- src/App.js
- src/component/MyPageItem.js
- src/pages/ImageDiary/HelpForAi.js
- src/pages/MyPages/APIKeyInput.js
- src/pages/MyPages/DiaryManagement.js
- src/pages/MyPages/MyPage.js
- src/pages/MyPages/UserUpdate.js
- src/recoil/apiKeyStore.js
- api 키 마이페이지에서 입력 받을수 있게 구현
- ![image](https://github.com/TUK-DP/frontend/assets/105588857/23a184cc-5846-4eab-88d8-da47c0894a60)
- ![image](https://github.com/TUK-DP/frontend/assets/105588857/ba98fdd3-25bd-46f2-8144-770115eee7f4)
> [feat] api 키 마이페이지에서 입력 받을수 있게 구현

- src/pages/Calendar/Draw.js
- Draw 의 캔바스에 있는 모든 그림 blob 변환 예외처리
- 모든 blob 데이터를 업로드하는 예외처리
> [refactor] 키워드별 사진 업로드, 변환 예외처리

- src/component/ImageDiary/Canvas.js
- src/component/ImageDiary/DrawTools.js
- src/component/ImageDiary/useDrawInputEvents.js
- src/pages/Calendar/Diary.js
- src/pages/Calendar/DiaryShow.js
- src/pages/Calendar/Draw.js
- src/pages/ImageDiary/HelpForAi.js
- src/recoil/canvasDrawingState.js
- src/styles/diary.css
- ai 의 사진을 수락한뒤 이전 키워드에 그렸던 내용이 사라지는 오류 해결
- ai 의 도움을 받아 그림을 배경에 넣게 되면 다른 일기의 똑같은 키워드에서 배경이 박힌채로 그림이 그려지는 오류 해결
- 그림일기 보여줄 때, border 삭제
> Fix/223 AI 사진 생성 후, 생기는 오류 해결

- package-lock.json
- package.json
- src/pages/Calendar/Diary.js
- 맨 위로 스크롤 올라가는 현상 수정
- react-textarea-autosize 라이브러리 적용
> Fix/226 일기 내용 입력 시 스크롤 올라가는 현상 수정
